#!/bin/bash
set -eo pipefail
shopt -s nullglob

REPO="$1"; BRANCH="$2"; IMAGE="$3"; BUILDCMD="$4"; MOUNT="$5"; IMAGE_NAME="$REPO/$BRANCH"

# copy the application into the container
id=$(cat | docker run -i -a stdin $ARGS $IMAGE /bin/bash -c "mkdir -p $MOUNT && tar -xC $MOUNT")
test "$(docker wait $id)" -eq 0
docker commit $id $IMAGE_NAME > /dev/null

# if a build process is required run the command on the container
if [[ $BUILDCMD ]]; then
	id=$(docker run -d $IMAGE_NAME $BUILDCMD)
	docker attach $id
	test "$(docker wait $id)" -eq 0
	docker commit $id $IMAGE_NAME > /dev/null
fi

echo "-----> Container built: $id"

echo "-----> Saving Image"
docker save $IMAGE_NAME > $REPO.$BRANCH.tar.gz

# echo "-----> Removing Build Artifacts"
# docker rmi $IMAGE_NAME:latest