#!/bin/bash
set -eo pipefail
#shopt -s nullglob

REPO="$1"; BRANCH="$2"; IMAGE="$REPO/$BRANCH"

echo "-----> Writing environment variables"
id=$(docker run -i -a stdin $IMAGE /bin/bash -c "mkdir -p /app/.profile.d && cat /app/.env > /app/.profile.d/app-env.sh")
test "$(docker wait $id)" -eq 0
docker commit $id $IMAGE > /dev/null