#!/bin/bash
set -eo pipefail
#shopt -s nullglob

# e.g. ./docker-start /vagrant/debug/repo.git HEAD repo master

REPO="$1"; BRANCH="$2"; IMAGE="$3"; CMD="$4"; IMAGE_NAME="$REPO/$BRANCH"

ARGS=""

PORT=$(cat "$TMP_WORK_DIR/Stackfile" | ./ini2arr.py $container port)
if [ -z "${PORT+xxx}" ]; then
	ARGS="$ARGS -p $PORT -e PORT=$port"
fi

id=$(docker run -d $ARGS $REPO/$BRANCH /bin/bash -c "/start web")