#!/bin/bash
set -eo pipefail
#shopt -s nullglob

TAR="$1"; APP_NAME="$2"; BRANCH="$3"; RUNCMD="$4"; PORT="$5"; DATA="$6"

echo "-----> Importing archive for $APP_NAME/$BRANCH:latest"
id=$(docker load -i ../role-builder/$TAR)

id=$(docker run -d -e PORT=$PORT $APP_NAME/$BRANCH:latest /bin/bash -c "$RUNCMD")
ipaddr=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $id)
echo "-----> Started container"
echo "       id: $id"
echo "       ip: $ipaddr"

echo "-----> Adding to load balancer"
if [ "$(redis-cli llen frontend:$APP_NAME.$BRANCH.cogclient.dev)" -eq "0" ]; then
	redis-cli rpush frontend:$APP_NAME.$BRANCH.cogclient.dev mywebsite
fi

redis-cli lrem frontend:$APP_NAME.$BRANCH.cogclient.dev -1 "http://$ipaddr:$PORT"
redis-cli rpush frontend:$APP_NAME.$BRANCH.cogclient.dev "http://$ipaddr:$PORT"