#!/bin/bash
set -eo pipefail
shopt -s nullglob

REPO="$1"; BRANCH="$2"; IMAGE="$3"; CMD="$4"; IMAGE_NAME="$REPO/$BRANCH"

id=$(docker run -d -p 5000 -e PORT=5000 $REPO/$BRANCH /bin/bash -c "/start web"")